apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton

labels:
  - pairs:
      app.kubernetes.io/part-of: saritasa-cicd
    includeSelectors: false

resources:
  - ns-tekton.yaml
  - quota-tekton.yaml
  - rbac-pac-task-reader.yaml
  - rbac-pipeline-sa.yaml
  - repository.yaml
