apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

labels:
  - pairs:
      app.kubernetes.io/part-of: saritasa-cicd
    includeSelectors: false

resources:
  - ns-dev.yaml
  - rbac-pipeline-sa-dev.yaml
